openapi: 3.0.4
info:
  title: Timetable log models
  description: Log models for logging services of marketplace
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        trip:
          $ref: '#/components/schemas/TimetableLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    TimetableLogModel:
      title: Модель лога для микросервиса Timetable
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
            - offers
        requestTrip:
          $ref: '#/components/schemas/TripLog'
        requestFilter:
          $ref: '#/components/schemas/TripFilterLog'
        responseTrip:
          $ref: '#/components/schemas/TripLog'
        responseTrips:
          type: array
          items:
            $ref: '#/components/schemas/TripLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    TripLog:
      title: Модель лога для маршрута
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        tripType:
          type: string
        ownerId:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    TripFilterLog:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string
        ownerId:
          type: string
        direction:
          type: string

